using System;
using Microsoft.VisualStudio.Shell;

namespace Microsoft.VisualStudio.ComponentDiagnostics
{
    class DiagnosticsColors
    {
        #region Autogenerated resource keys
        // These resource keys are generated by VsThemeEditor, and should be replaced when new colors are added to this category.
        public static readonly Guid Category = new Guid("cedc88e0-008f-4e01-a3b2-933604afcdcd");

        private static ThemeResourceKey _NSTM_AllTextColorKey;
        private static ThemeResourceKey _NSTM_AllTextBrushKey;
        public static ThemeResourceKey NSTM_AllTextColorKey { get { return _NSTM_AllTextColorKey ?? (_NSTM_AllTextColorKey = new ThemeResourceKey(Category, "NSTM_All", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey NSTM_AllTextBrushKey { get { return _NSTM_AllTextBrushKey ?? (_NSTM_AllTextBrushKey = new ThemeResourceKey(Category, "NSTM_All", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _NSTM_NoneTextColorKey;
        private static ThemeResourceKey _NSTM_NoneTextBrushKey;
        public static ThemeResourceKey NSTM_NoneTextColorKey { get { return _NSTM_NoneTextColorKey ?? (_NSTM_NoneTextColorKey = new ThemeResourceKey(Category, "NSTM_None", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey NSTM_NoneTextBrushKey { get { return _NSTM_NoneTextBrushKey ?? (_NSTM_NoneTextBrushKey = new ThemeResourceKey(Category, "NSTM_None", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _NSTM_OnlyTopLevelTextColorKey;
        private static ThemeResourceKey _NSTM_OnlyTopLevelTextBrushKey;
        public static ThemeResourceKey NSTM_OnlyTopLevelTextColorKey { get { return _NSTM_OnlyTopLevelTextColorKey ?? (_NSTM_OnlyTopLevelTextColorKey = new ThemeResourceKey(Category, "NSTM_OnlyTopLevel", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey NSTM_OnlyTopLevelTextBrushKey { get { return _NSTM_OnlyTopLevelTextBrushKey ?? (_NSTM_OnlyTopLevelTextBrushKey = new ThemeResourceKey(Category, "NSTM_OnlyTopLevel", ThemeResourceKeyType.ForegroundBrush)); } }
        #endregion
    }
}
