//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ComponentDiagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ComponentDiagnostics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProvider was called wiht a null data model argument..
        /// </summary>
        internal static string AddProvider_ArgumentNull {
            get {
                return ResourceManager.GetString("AddProvider_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested diagnostics provider has already been added..
        /// </summary>
        internal static string AddProvider_ProviderAlreadyAdded {
            get {
                return ResourceManager.GetString("AddProvider_ProviderAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested diagnostics provider is not registered..
        /// </summary>
        internal static string AddProvider_ProviderNotRegistered {
            get {
                return ResourceManager.GetString("AddProvider_ProviderNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProviderIndirect was called with a null diagnostics provider argument..
        /// </summary>
        internal static string AddProviderIndirect_ArgumentNull {
            get {
                return ResourceManager.GetString("AddProviderIndirect_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the Component Diagnostics tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component diagnostics service provider is not available..
        /// </summary>
        internal static string ComponentDiagnosticsServiceUnavailable {
            get {
                return ResourceManager.GetString("ComponentDiagnosticsServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory returned a valid UI Element that supports IVsUIWpfElement, but CreateFrameworkElementFailed with error code 0x{0:x}.
        /// </summary>
        internal static string CreateFrameworkElementFailed {
            get {
                return ResourceManager.GetString("CreateFrameworkElementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory threw a TargetInvocationException during CreateFrameworkElement. This typically indicates a bug in the WPF control being instantiated. The inner exception message follows.
        ///
        ///{0}.
        /// </summary>
        internal static string CreateFrameworkElementTargetInvocationException {
            get {
                return ResourceManager.GetString("CreateFrameworkElementTargetInvocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the diagnostics provider view (UI Factory:{0}, element {1}). The UI factory service returned error code 0x{2:x}.
        /// </summary>
        internal static string CreateUIElementFailed {
            get {
                return ResourceManager.GetString("CreateUIElementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory returned a valid view, but the view failed to create.  The UI element&apos;s GetUIObject method returned error code 0x{0:x}.
        /// </summary>
        internal static string GetUIObjectFailed {
            get {
                return ResourceManager.GetString("GetUIObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory&apos;s CreateUIElement method was called with an unrecognized element ID (DWORD).
        /// </summary>
        internal static string InvalidElementId {
            get {
                return ResourceManager.GetString("InvalidElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory&apos;s CreateUIElement method was called with an unrecognized factory GUID.
        /// </summary>
        internal static string InvalidFactoryId {
            get {
                return ResourceManager.GetString("InvalidFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A view could not be created because the selected diagnostics provider supplied an empty data model..
        /// </summary>
        internal static string ProviderIsNull {
            get {
                return ResourceManager.GetString("ProviderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested provider was not added or has already been removed..
        /// </summary>
        internal static string RemoveProvider_AlreadyInactive {
            get {
                return ResourceManager.GetString("RemoveProvider_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveProvider was called with an invalid cookie value..
        /// </summary>
        internal static string RemoveProvider_InvalidCookie {
            get {
                return ResourceManager.GetString("RemoveProvider_InvalidCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected diagnostics provider is not currently active. Select a different active provider from the list on the left..
        /// </summary>
        internal static string SelectedProviderIsInactive {
            get {
                return ResourceManager.GetString("SelectedProviderIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Diagnostics.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI Factory returned a valid UI Element but it does not support WPF and cannot be used in this window. (Actual type:{0}).
        /// </summary>
        internal static string ViewIsNotAFrameworkElement {
            get {
                return ResourceManager.GetString("ViewIsNotAFrameworkElement", resourceCulture);
            }
        }
    }
}
